#!/bin/bash

if[ -z "$PYFILE" ]; then
  echo "Error: PYFILE environment variable is not set or empty."
  exit 1
fi

if [ ! -f "$PYFILE" ]; then
  echo "Error: File '$PYFILE' does not exist."
  exit 1
fi

# Run the Python script
python3 "$PYFILE"